### ISSUE TITLE
Nullpointer in template.

### ISSUE THREAD

**Issue by stefandroog** [heinoldenhuis/home_assistant_area_waste#2]
Ik gebruik jouw plugin in HA (0.108.6). Hiervoor dank! Heb in mijn configuration.yaml het script staan wat gelijk is aan: https://github.com/heinoldenhuis/home_assistant_area_waste/blob/master/example.md

Ik gebruik de automation.yaml niet.

Nu zie ik ik mijn logs onderstaande melding. Plugin lijkt verder wel goed te werken. Er gaat blijkbaar een None in strptime, wat niet is toegestaan. Waarschijnlijk komt er niets terug vanuit state_attr('sensor.waste_today', 'date').

`2020-04-19 15:47:35 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-19 15:47:40 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for areawaste which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-19 15:47:44 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-04-19 15:47:44 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 5 seconds.
2020-04-19 15:47:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.date_today fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/template/sensor.py", line 224, in async_update
    self._state = self._template.async_render()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 221, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 813, in strptime
    return datetime.strptime(string, fmt)
TypeError: strptime() argument 1 must be str, not None
2020-04-19 15:47:51 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template GFT afval: UndefinedError: 'str object' has no attribute 'strftime'
2020-04-19 15:47:51 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Plastic: UndefinedError: 'str object' has no attribute 'strftime'
2020-04-19 15:47:51 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Restafval: UndefinedError: 'str object' has no attribute 'strftime'
2020-04-19 15:47:55 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-04-19 15:47:55 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 10 seconds.`

**Comment by heinoldenhuis** [comment]
Hallo Stefan,

Had zelf ook het issue. Het gebeurde bij mij als ik HA start en de sensors nog niet zijn geladen.
De fouten worden namelijk gegeven door de template sensoren.
Deze sensoren lezen de Area Waste sensoren die op dat moment nog geen data hebben.
Op dat moment wordt in de template sensor een niet geldige waarde door de functie strftime omgezet naar een datum.

Zou je de onderstaande configuratie eens willen proberen? Deze werkt nu bij mij en dan zal ik het voorbeeld een keer bijwerken.

```
- platform: template
  sensors:
    date_today: 
      friendly_name: 'Datum'
      value_template: >
        {% set months = ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"] %}
        {% set weekdays = ["zondag", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag"] %}
        {% if state_attr('sensor.waste_today', 'date') != None %}
        {% set date = strptime(state_attr('sensor.waste_today', 'date'), '%Y-%m-%d') %}
        {% set month = months[date.strftime('%m') | int -1] %}
        {% set weekday = weekdays[date.strftime('%w') | int] %}
        {{ weekday + ' ' + date.strftime('%d') + ' ' + month + ' '+ date.strftime('%Y') }}
        {% else %}
          Onbekend
        {% endif %}
    waste_green_formatted:
      friendly_name: 'GFT afval'
      entity_picture_template: /local/waste/green_icon.png
      value_template: >
        {% set months = ["jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec"] %}
        {% set weekdays = ["Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za"] %}
        {% if states('sensor.waste_green') != 'unknown' %}
        {% set date = strptime(states('sensor.waste_green'), '%Y-%m-%d') %}
        {% set month = months[date.strftime('%m') | int -1] %}
        {% set weekday = weekdays[date.strftime('%w') | int] %}
        {{ weekday + ' ' + date.strftime('%d') + ' ' + month }}
        {% else %}
          Onbekend
        {% endif %}
    waste_plastic_formatted:
      friendly_name: 'Plastic'
      entity_picture_template: /local/waste/plastic_icon.png
      value_template: >
        {% set months = ["jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec"] %}
        {% set weekdays = ["Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za"] %}
        {% if states('sensor.waste_plastic') != 'unknown' %}
        {% set date = strptime(states('sensor.waste_plastic'), '%Y-%m-%d') %}
        {% set month = months[date.strftime('%m') | int -1] %}
        {% set weekday = weekdays[date.strftime('%w') | int] %}
        {{ weekday + ' ' + date.strftime('%d') + ' ' + month }}
        {% else %}
          Onbekend
        {% endif %}
    waste_residual_formatted:
      friendly_name: 'Restafval'
      entity_picture_template: /local/waste/grey_icon.png
      value_template: >
        {% set months = ["jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec"] %}
        {% set weekdays = ["Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za"] %}
        {% if states('sensor.waste_residual') != 'unknown' %}
        {% set date = strptime(states('sensor.waste_residual'), '%Y-%m-%d') %}
        {% set month = months[date.strftime('%m') | int -1] %}
        {% set weekday = weekdays[date.strftime('%w') | int] %}
        {{ weekday + ' ' + date.strftime('%d') + ' ' + month }}
        {% else %}
          Onbekend
        {% endif %}
    waste_today_formatted:
      friendly_name: 'Vandaag'
      value_template: >
        {% if state_attr('sensor.waste_today', 'trash_type') == "GREEN" %}GFT afval{%
        elif state_attr('sensor.waste_today', 'trash_type') == "GREY" %}Restafval{%
        elif state_attr('sensor.waste_today', 'trash_type') == "PLASTIC" %}Plastic{%
        else %}Geen{% endif %}
    waste_tomorrow_formatted:
      friendly_name: 'Morgen'
      value_template: >
        {% if state_attr('sensor.waste_tomorrow', 'trash_type') == "GREEN" %}GFT afval{%
        elif state_attr('sensor.waste_tomorrow', 'trash_type') == "GREY" %}Restafval{%
        elif state_attr('sensor.waste_tomorrow', 'trash_type') == "PLASTIC" %}Plastic{%
        else %}Geen{% endif %}
```

**Comment by stefandroog** [comment]
Dit werkt! Geen foutmelding meer in de log. Ik kreeg ze ook alleen tijdens het starten.
